### ISSUE TITLE
TypeError: Cannot read property 'callMethod$2' of null

### ISSUE THREAD

**Issue by austincummings** [DirectMyFile/atom.dart#1]
Hey @kaendfinger,

I wrote a small bit of code to try and call `addBottomPanel()` on the `atom.workspace`. I get an error though. Below is the code and the stack trace. 

**Code**

``` dart
import 'dart:html';
import 'package:atom/atom.dart';

class DartFileOutline {
  Element get element => _element;
  void set element(val) => _element = val;
  Element _element;

  DartFileOutline() {
    _element = new DivElement()..text = 'Hello world';
  }
}

void main() {
  atom.workspace.addBottomPanel(new DartFileOutline().element);
}
```

**Stack Trace**

```
TypeError: Cannot read property 'callMethod$2' of null
    at dart.main (C:\Users\austin\Workspace\atom-dart\index.js:3608:11)
    at C:\Users\austin\Workspace\atom-dart\index.js:5587:7
    at init.currentScript (C:\Users\austin\Workspace\atom-dart\index.js:5567:5)
    at C:\Users\austin\Workspace\atom-dart\index.js:5582:3
    at Object.<anonymous> (C:\Users\austin\Workspace\atom-dart\index.js:5591:3)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (C:\Users\austin\AppData\Local\atom\app-0.194.0\resources\app.asar\src\babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

**Comment by austincummings** [comment]
Actually I just solved it. I needed to wait for the package to activate.

``` dart
void activate() {
  atom.workspace.addBottomPanel(new DartFileOutline().element);
}

main() => onPackageActivated(activate);
```
